# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Legacy
version:      1.2501
version_from: lib/Test/Legacy.pm
installdirs:  site
requires:
    Test::Builder:                 0.21_01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.24_01
